[package]
name = "mandelbrot"
version = "0.1.0"
edition = "2021"

[lib]
name = "mandelbrot"
crate-type = ["cdylib"]

[dependencies]
image = "0.24.3"
ndarray = "0.15.6"
palette = "0.6.1"
pyo3 = { version = "0.16.5", features = ["extension-module"] }